[package]
name = "scratch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray={version = "0.15.6", features = ["approx-0_5"]}
approx="0.5.0"
serde="1.0"
serde-pickle="1.1.1"

